### ISSUE TITLE
Issues from checklist review 11/30

### ISSUE THREAD

**Issue by ghost** [sparkfun/IOIO-OTG#1]
1.) D1, D2, Q1, Q2, Q3 need value in schematic.

2.) Looks like the design is still using the old sparkfun 2-layer DRU

Thanks!

**Comment by lewispg228** [comment]
Thanks Kade!

Two things to note:

1) I added in text objects on the value layer separate from device. I will discuss at the DFM committee this week whether it will officially be standard to include in the symbol at the library level. But for this design to move forward, I'd like to just leave them as separate text objects floating in the wild.

2) When I moved to the TIGHT dru, I noticed that this also decreased the annular rings on vias, so I also bumped the vias up to 15 mil (they were previously 12 mil) Due to the tighter restring in the TIGHT dru each via actually ended up having a smaller overall footprint, and so it didn't necessitate moving anything and/or re-routing.

Please check it out and let me know.

Thanks!

**Comment by ghost** [comment]
Looks good. Thanks!
